# Lecture 2

## What is data with dependencies

### What is independent data

Broadly, having knowledge about one observation should not give you knowledge about other observations in your dataset.

For example, if we flip a coin ten times, knowing the result of the first coin toss (heads) will not give us knowledge about the subsequent 9 coin tosses.

### What is data with dependencies

In reality, most data have dependencies, so we will focus on some of the most important kinds that will severely impact your analyses if you do not identify them.

### Repeated measures/longitudinal data

If you have a dataset with repeated measures (e.g. some people in your cohort have more than one observation), then the repeated observations on each person cause dependencies in the data. That is, if a person has their weight measured five times, then just by knowing their first weight you can have a good guess at what their subsequent weights will be.

### Grouped/clustered data

Repeated measures data is a type of clustered data, where each person is their own cluster. There can be many kinds of clusters, for example:

- Data sampled from multiple hospitals could have the hospital as the cluster variable
- Data sampled from multiple countries could have the country as the cluster variable
- Data sampled from multiple counties/municipalities could have the country/municipality as the cluster variable
- If it is a study of children, and multiple children from each mother are included, then the mother could be the cluster variable

### Matched data

Inside case-control studies, for each case a control (or multiple cases) can be selected to have similar attributes. For example, for each case, a control can be selected with a similar age. These controls have been "matched" to a case, and have introduced dependencies into the data.

## Analysing data with dependencies

### Mixed effects regression

Mixed effects regression should be used for grouped/clustered data (and subsequently repeated measures/longitudinal data)

### Identifying when conditional logistic regression models should be used

Conditional logistic regression should be used for matched data

## (TBD) Understanding the different imputation methods used when lab data is below the limit of detection (LOD)

## (TBD) Understanding the best practices for data files and project folders

