# Solutions

## Poisons Information Center

Scenario:

- Approximately 40 000 calls per year
- The frequency of calls regarding different drugs/plants etc varies greatly, from a couple per year to thousands per year, so most probably one method will not cover everything.
- The registration of data is done while on the phone, and we know there are mistakes
- Only the field Kommentar has free text

Question: Is the number of calls regarding women aged 15-19 who have been exposed to paracetamol rising or falling over the years.

**Aim**: Hypothesis testing (maybe estimation of yearly effect)

**Outcome**: Count data (number of calls regarding women aged 15-19 who have been exposed to paracetamol)

**Exposure**: Continuous (year)

**Parametric assumptions**: None

**Dependencies**: None

**Appropriate Method**: Negative-binomial regression

**Example STATA code**:

```
nbreg number_of_calls year
```

## Norwegian Water Pipes

Scenario:

- 146 waterworks in 19 counties in Norway
- Each waterwork uses pipes to deliver water to households
- Information on each waterwork:
  * Length of pipes made out of asbestos (in meters)
  * Length of pipes made out of iron/steel (in meters)
  * Length of pipes made out of PVC (in meters)
  * Length of pipes made out of PE/PEH (in meters)
  * Length of pipes made out of other (in meters)
  * Length of pipes made out of unknown (in meters)
  * Length of pipes installed before 1910 (in meters)
  * Length of pipes installed in 1910-1940 (in meters)
  * Length of pipes installed in 1941-1970 (in meters)
  * Length of pipes installed in 1971-2000 (in meters)
  * Length of pipes installed after 2000 (in meters)
  * Length of pipes installed during an unknown period (in meters)
- Each year, some new pipes are laid to extend the network
- Each year, some pipes are replaced
- Interruption in water delivery is estimated in hours per calendar year
- Data is only for 2015

Question: Is there an association between "interuption in water delivery" and "type of pipe material" and "pipe installation period"

**Aim**: Hypothesis testing

**Outcome**: Count (hours interruption in water delivery)

**Exposure**: 12 continuous variables

**Parametric assumptions**: None

**Dependencies**: No

**Appropriate Method**: Negative-binomial regression

**Example STATA code**:

```
nbreg hoursInterrupted pipesAsbestos pipesIronSteel pipesPVC ... pipes1910 ...
```

## Early warning system (EWS) for waterborne outbreaks (part 1)

Scenario:

- NorSySS is a syndromic surveillance system for infectious diseases, run by the NIPH. 
- The system is based on national ICPC coded consultation data from general practice in Norway.
- We want to study to what extent NorSySS can serve as an early warning system for local waterborne outbreaks by alerting us to increases in consultation rates for syndromes indicative of gastrointestinal diseases.  
- Retrospective syndrome data (number of gastritis cases, per week, for each municipality) from NorSySS will be aligned with outbreak data (outbreak=yes/no) from the national web-based outbreak rapid alert system (Vesuv) for the period 2006-2017.

Question: Is there an association between "recorded outbreak" and "number of gastritis cases"

**Aim**: Hypothesis testing

**Outcome**: Binary (recorded outbreak)

**Exposure**: Count (number of gastritis cases)

**Parametric assumptions**: None

**Dependencies**: Yes (longitudinal data by municipality)
 
**Appropriate Method**: Mixed effects logistic regression 
 
## Early warning system (EWS) for waterborne outbreaks (part 2)

Scenario:

- We have weekly data on water quality from water works (e.g. pH, turbidity)
- We have weekly number of gastritis cases, per week, for each municipality
- We hope to increase the knowledge about causes of waterborne outbreaks and to develop an improved surveillance system for early detection of future outbreaks.

Question: Is there an association between "weekly number of gastritis cases" and "water quality from the water works"

**Aim**: Hypothesis testing

**Outcome**: Count (number of gastritis cases)

**Exposure**: Continuous (pH, turbidity)

**Parametric assumptions**: None

**Dependencies**: Yes (longitudinal data by municipality)
 
**Appropriate Method**: Mixed effects negative-binomial regression 
 
## Incidents in the water supply system and illness

Scenario:

- Data from the water works operation (pH, turbidity) will be linked to health outcome among recipients of the drinking water.
- The study will be a prospective cohort study, with data collected among a random selection of water works. 
- Data from the recruited water works will be collected in the period autumn 2017 and the 12 following months.
- Approximately 350 water works will be recruited to provide monthly data on hygienic critical points related to operation and maintenance of the water supply system.
- In parallel, a cohort of approximately 9000 persons, served by water from the recruited water works, will submit monthly reports on symptoms that may indicate gastrointestinal illness.
- The data collection will start in the autumn of 2017 and continue for 12 months.

Question: Is water quality a risk factor for getting sick?

**Aim**: Hypothesis testing

**Outcome**: Binary (sick yes/no)

**Exposure**: Continuous (pH, turbidity)

**Parametric assumptions**: None

**Dependencies**: Yes (longitudinal data by person, clustered by waterwork and/or municipality)
 
**Appropriate Method**: Mixed effects logistic regression 
 
## Compliance with boil water advisories and perception of risks

Scenario:

- In this study, the compliance and perception of risks among the public with boil water advisories (BWAs) will be examined.
- Although BWAs is a common practice among water utilities, a meta-study suggest that there is limited information and studies on the compliance of BWAs.
- This part, the compliance and perception of risks will be done by studying the perception of and adherence to BWAs among the consumers of drinking water in Bærum municipality.
- Even though the drinking water in Bærum is considered to have good quality, Bærum – like many water works – experience situations of pressure drops due to breaks and maintenance.
- Research has shown that these situations may lead to an increased risk of gastrointestinal infections, and due to this the municipality of Bærum has issued a precautionary BWAs to the affected consumers with every water outage during the last 5-6 years.
- Every year, some 12,000-22,000 consumers have received a precautionary BWA.
- The purpose of these precautionary BWAs is to prevent health consequences caused by possible contamination of water. However, we know little about the consumer’s knowledge about why they receive these BWAs, as well as the way the consumers perceive and adhere to these BWAs.
- This is a cross-sectional study.
- A web-survey will be presented to a randomly selected sample of consumers who received a BWA in Bærum in 2017.
- The web-survey asks about adherence (yes/no) and demographics (e.g. age, sex, income)

Question: Estimate adherence by demographics (and identify if it differs by demographics)

**Aim**: Estimation and hypothesis testing

**Outcome**: Binary (adhberence yes/no)

**Exposure**: Binary (sex), Categorical (age, income)

**Parametric assumptions**: None

**Dependencies**: No ("randomly selected sample of consumers")
 
**Appropriate Method**: Logistic regression 
 



