<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>A Compendium Of Statistics Questions</title>
  <meta name="description" content="A compendium of commonly asked statistical questions.">
  <meta name="generator" content="bookdown 0.4 and GitBook 2.6.7">

  <meta property="og:title" content="A Compendium Of Statistics Questions" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A compendium of commonly asked statistical questions." />
  <meta name="github-repo" content="raubreywhite/raubreywhite.github.io" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="A Compendium Of Statistics Questions" />
  
  <meta name="twitter:description" content="A compendium of commonly asked statistical questions." />
  

<meta name="author" content="Richard White">


<meta name="date" content="2017-06-07">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="docker.html">
<link rel="next" href="outcomes.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="/">Home</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Purpose</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="folder-structure.html"><a href="folder-structure.html"><i class="fa fa-check"></i><b>3</b> Folder structure</a></li>
<li class="chapter" data-level="4" data-path="docker.html"><a href="docker.html"><i class="fa fa-check"></i><b>4</b> Docker</a><ul>
<li class="chapter" data-level="4.1" data-path="docker.html"><a href="docker.html#what-is-docker-and-why-is-it-good"><i class="fa fa-check"></i><b>4.1</b> What is Docker, and why is it good?</a></li>
<li class="chapter" data-level="4.2" data-path="docker.html"><a href="docker.html#what-is-repl"><i class="fa fa-check"></i><b>4.2</b> What is REPL?</a></li>
<li class="chapter" data-level="4.3" data-path="docker.html"><a href="docker.html#what-is-vim"><i class="fa fa-check"></i><b>4.3</b> What is VIM?</a></li>
<li class="chapter" data-level="4.4" data-path="docker.html"><a href="docker.html#what-is-vim-slime"><i class="fa fa-check"></i><b>4.4</b> What is vim-slime?</a></li>
<li class="chapter" data-level="4.5" data-path="docker.html"><a href="docker.html#which-docker-containers-should-i-use"><i class="fa fa-check"></i><b>4.5</b> Which Docker containers should I use?</a></li>
<li class="chapter" data-level="4.6" data-path="docker.html"><a href="docker.html#putting-it-all-together"><i class="fa fa-check"></i><b>4.6</b> Putting it all together</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-regression-vs-anova.html"><a href="linear-regression-vs-anova.html"><i class="fa fa-check"></i><b>5</b> Linear Regression vs ANOVA</a><ul>
<li class="chapter" data-level="5.1" data-path="linear-regression-vs-anova.html"><a href="linear-regression-vs-anova.html#summary"><i class="fa fa-check"></i><b>5.1</b> Summary</a></li>
<li class="chapter" data-level="5.2" data-path="linear-regression-vs-anova.html"><a href="linear-regression-vs-anova.html#empirical-evidence"><i class="fa fa-check"></i><b>5.2</b> Empirical evidence</a></li>
<li class="chapter" data-level="5.3" data-path="linear-regression-vs-anova.html"><a href="linear-regression-vs-anova.html#statistical-proof"><i class="fa fa-check"></i><b>5.3</b> Statistical proof</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="outcomes.html"><a href="outcomes.html"><i class="fa fa-check"></i><b>6</b> Outcomes</a><ul>
<li class="chapter" data-level="6.1" data-path="outcomes.html"><a href="outcomes.html#length-of-stay"><i class="fa fa-check"></i><b>6.1</b> Length of stay</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-imputation.html"><a href="multiple-imputation.html"><i class="fa fa-check"></i><b>7</b> Multiple imputation</a><ul>
<li class="chapter" data-level="7.1" data-path="multiple-imputation.html"><a href="multiple-imputation.html#longitudinal-data"><i class="fa fa-check"></i><b>7.1</b> Longitudinal data</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regressions-using-survey-data.html"><a href="regressions-using-survey-data.html"><i class="fa fa-check"></i><b>8</b> Regressions using survey data</a><ul>
<li class="chapter" data-level="8.1" data-path="regressions-using-survey-data.html"><a href="regressions-using-survey-data.html#literature-summary"><i class="fa fa-check"></i><b>8.1</b> Literature summary</a></li>
<li class="chapter" data-level="8.2" data-path="regressions-using-survey-data.html"><a href="regressions-using-survey-data.html#setup"><i class="fa fa-check"></i><b>8.2</b> Setup</a></li>
<li class="chapter" data-level="8.3" data-path="regressions-using-survey-data.html"><a href="regressions-using-survey-data.html#case-control-studies"><i class="fa fa-check"></i><b>8.3</b> Case-control studies</a></li>
<li class="chapter" data-level="8.4" data-path="regressions-using-survey-data.html"><a href="regressions-using-survey-data.html#oversampling-a-population-with-a-higher-level-of-the-outcome"><i class="fa fa-check"></i><b>8.4</b> Oversampling a population with a higher level of the outcome</a></li>
<li class="chapter" data-level="8.5" data-path="regressions-using-survey-data.html"><a href="regressions-using-survey-data.html#oversampling-a-population-with-a-higher-level-of-the-outcome-and-exposure"><i class="fa fa-check"></i><b>8.5</b> Oversampling a population with a higher level of the outcome and exposure</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="matching.html"><a href="matching.html"><i class="fa fa-check"></i><b>9</b> Matching</a><ul>
<li class="chapter" data-level="9.1" data-path="matching.html"><a href="matching.html#in-case-control-studies"><i class="fa fa-check"></i><b>9.1</b> In case control studies</a></li>
<li class="chapter" data-level="9.2" data-path="matching.html"><a href="matching.html#in-non-case-control-studies"><i class="fa fa-check"></i><b>9.2</b> In non-case control studies</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Compendium Of Statistics Questions</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression-vs-anova" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Linear Regression vs ANOVA</h1>
<div id="summary" class="section level2">
<h2><span class="header-section-number">5.1</span> Summary</h2>
<p>Many ANOVA computations can be performed using linear regression models, with nested/hierarchical problems requiring mixed effects regression models <span class="citation">(Gelman <a href="#ref-gelman_analysis_2005">2005</a>)</span>.</p>
</div>
<div id="empirical-evidence" class="section level2">
<h2><span class="header-section-number">5.2</span> Empirical evidence</h2>
<p>First we create some data, shown in Figure <a href="linear-regression-vs-anova.html#fig:anova-data">5.1</a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

<span class="kw">set.seed</span>(<span class="dv">4</span>)
x &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>:<span class="dv">2</span>,<span class="dv">100</span>)
y &lt;-<span class="st"> </span>(x<span class="dv">+1</span>)/<span class="dv">7</span> +<span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(x))
data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">y=</span>y,<span class="dt">x=</span>x)

q &lt;-<span class="st"> </span><span class="kw">ggplot</span>(data,<span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y,<span class="dt">group=</span>x))
q &lt;-<span class="st"> </span>q +<span class="st"> </span><span class="kw">geom_boxplot</span>()
<span class="kw">print</span>(q)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:anova-data"></span>
<img src="a-compendium-of-statistics-questions_files/figure-html/anova-data-1.png" alt="Three diffferent groups (x=0, 1, 2)" width="80%" />
<p class="caption">
Figure 5.1: Three diffferent groups (x=0, 1, 2)
</p>
</div>
<p>Then we establish the linear regression model</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \epsilon_i
\]</span> where <span class="math inline">\(i=1,\dots\,n\)</span> and <span class="math inline">\(\epsilon_i \sim N(0,\sigma^2)\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit &lt;-<span class="st"> </span><span class="kw">lm</span>(y ~<span class="st"> </span><span class="kw">factor</span>(x), data)
<span class="kw">summary</span>(fit)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ factor(x), data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.48573 -0.70825 -0.05413  0.67424  2.59549 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  0.06488    0.09662   0.672  0.50239   
## factor(x)1   0.23052    0.13664   1.687  0.09264 . 
## factor(x)2   0.40818    0.13664   2.987  0.00305 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9662 on 297 degrees of freedom
## Multiple R-squared:  0.02933,    Adjusted R-squared:  0.02279 
## F-statistic: 4.487 on 2 and 297 DF,  p-value: 0.01203</code></pre>
<p>and we can see that the F-test corresponding to</p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = 0
\]</span> <span class="math display">\[
H_1: \text{Not } H_0
\]</span> has a p-value of 0.01203.</p>
<p>We then perform a one-way ANOVA assuming equal variances, with: <span class="math display">\[
H_0: \bar{y}_{\text{x=0}} = \bar{y}_{\text{x=1}} = \bar{y}_{\text{x=2}}
\]</span> <span class="math display">\[
H_1: \text{Not } H_0
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">oneway.test</span>(y~x,<span class="dt">data =</span> data,<span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  One-way analysis of means
## 
## data:  y and x
## F = 4.4869, num df = 2, denom df = 297, p-value = 0.01203</code></pre>
<p>and we again see that the p-value is 0.01203.</p>
<p>However, when running a one-way ANOVA assuming unequal variances</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">oneway.test</span>(y~x,<span class="dt">data =</span> data,<span class="dt">var.equal =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  y and x
## F = 4.5345, num df = 2.00, denom df = 197.56, p-value = 0.01187</code></pre>
<p>We see that the p-value is 0.01187, which is not the same as the linear regression.</p>
</div>
<div id="statistical-proof" class="section level2">
<h2><span class="header-section-number">5.3</span> Statistical proof</h2>
<p>The following proof was taken from <span class="citation">(Hardy <a href="#ref-hardy_difference_2012">2012</a>)</span></p>
<p>Suppose your data set consists of a set <span class="math inline">\((x_i,y_i)\)</span> for <span class="math inline">\(i=1,\ldots,n\)</span> and you want to look at the dependence of <span class="math inline">\(y\)</span> on <span class="math inline">\(x\)</span>.</p>
<p>Suppose you find the values <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that minimize the residual sum of squares <span class="math display">\[
\sum_{i=1}^n (y_i - (\beta_0+\beta_1 x_i))^2.
\]</span> Then you take <span class="math inline">\(\hat y = \hat\beta_0+ \hat\beta_1 x\)</span> to be the predicted <span class="math inline">\(y\)</span>-value for any (not necessarily already observed) <span class="math inline">\(x\)</span>-value. That’s linear regression.</p>
<p>Now consider decomposing the total sum of squares <span class="math display">\[
\sum_{i=1}^n (y_i - \bar y)^2 \text{ where }\bar y = \frac{y_1+\cdots+y_n}{n}
\]</span> with <span class="math inline">\(n-1\)</span> degrees of freedom, into “explained” and “unexplained” parts: <span class="math display">\[
\underbrace{\sum_{i=1}^n ((\hat\beta_0+\hat\beta_1 x_i) - \bar y)^2}_{\text{explained}}\  +\  \underbrace{\sum_{i=1}^n (y_i - (\hat\beta_0+\hat\beta_1 x_i))^2}_{\text{unexplained}}.
\]</span> with <span class="math inline">\(1\)</span> and <span class="math inline">\(n-2\)</span> degrees of freedom, respectively. That’s analysis of variance, and one then considers things like F-statistics <span class="math display">\[
F = \frac{\sum_{i=1}^n ((\hat\beta_0+\hat\beta_1 x_i) - \bar y)^2/1}{\sum_{i=1}^n (y_i - (\hat\beta_0+\hat\beta_1 x_i))^2/(n-2)}.
\]</span> <em>This</em> F-statistic tests the null hypothesis <span class="math inline">\(\beta_1=0\)</span>, which is the same as the traditional ANOVA: <span class="math display">\[
F = \frac{\text{Between SS}/\text{df}}{\text{Within SS}/\text{df}}.
\]</span></p>
<p>One often first encounters the term “analysis of variance” when the predictor is categorical, so that you’re fitting the model <span class="math display">\[
y = \beta_0 + \beta_i
\]</span> where <span class="math inline">\(i\)</span> identifies which category is the value of the predictor. If there are <span class="math inline">\(k\)</span> categories, you’d get <span class="math inline">\(k-1\)</span> degrees of freedom in the numerator in the F-statistic, and usually <span class="math inline">\(n-k\)</span> degrees of freedom in the denominator. But the distinction between regression and analysis of variance is still the same for this kind of model.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-gelman_analysis_2005">
<p>Gelman, Andrew. 2005. “Analysis of Variance? Why It Is More Important Than Ever.” <em>The Annals of Statistics</em> 33 (1): 1–53. doi:<a href="https://doi.org/10.1214/009053604000001048">10.1214/009053604000001048</a>.</p>
</div>
<div id="ref-hardy_difference_2012">
<p>Hardy, Michael. 2012. “Difference Between Regression Analysis and Analysis of Variance? - Cross Validated.” <a href="http://stats.stackexchange.com/questions/34616/difference-between-regression-analysis-and-analysis-of-variance/34618" class="uri">http://stats.stackexchange.com/questions/34616/difference-between-regression-analysis-and-analysis-of-variance/34618</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="docker.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="outcomes.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/raubreywhite/raubreywhite.github.io/edit/master/xsrc_book/04-regression-vs-anova.Rmd",
"text": "Edit"
},
"download": ["a-compendium-of-statistics-questions.pdf"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
